name: 'Get Latest Tag'
description: 'Get the latest tag from git and outputs that for use in other actions'
branding:
  icon: 'tag'
  color: 'gray-dark'
inputs:
  fallback:
    description: 'Fallback tag to use when no previous tag can be found'
    required: false
  pattern:
    description: 'Limit tags to ones matching given shell glob. If pattern lacks ?, *, or [, /* at the end is implied'
    required: false
outputs:
  tag:
    description: 'Latest tag'
  timestamp:
    description: 'Latest tag timestamp'
runs:
  using: 'node12'
  main: 'main.js'
